development:
  adapter: postgresql
  encoding: unicode
  database: rails-chat-tutorial_development
  pool: 5
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: rails-chat-tutorial_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rails-chat-tutorial_production
  pool: 5
  username: postgres
  password:

